version: '2'
services:
  SSO:
    image: node:12.10.0-alpine
    ports:
      - 8888:8888/tcp
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
